### ISSUE TITLE
make shortcuts optional

### ISSUE THREAD

**Issue by DaWolfi** [AlexanderPro/SmartContextMenu#14]
Hi @AlexanderPro,
tested this awsome programm right now, works great, thanks!

Is it possible to make the shortcuts for transparency optional, or at least configurable?
I've been using them for quite a long time in other software, so it would be nice if you could help me with this!

**Comment by AlexanderPro** [comment]
Hi @DaWolfi,

You can change or reset shortcuts in the System tray -> Settings dialog (Menu tab).

Сhange
![HotKeySettings2](https://github.com/AlexanderPro/SmartContextMenu/assets/8102586/5b971f06-decd-485a-8839-0636cdcd2e11)

Reset
![HotKeySettings](https://github.com/AlexanderPro/SmartContextMenu/assets/8102586/fb75299b-ed63-4b59-88b4-20a6dc9aa594)

**Comment by DaWolfi** [comment]
Thanks man, I should have spent more time studying the settings first 🙈
