### ISSUE TITLE
Allways on top

### ISSUE THREAD

**Issue by btfls** [AlexanderPro/SmartContextMenu#17]

**Comment by btfls** [comment]
Hi, seems not to work in many windows under Windows 10,
Regards

**Comment by AlexanderPro** [comment]
Hi @btfls ,

What OS version and window do you use?

**Comment by bleeme** [comment]
Hi, I'm on...

OS Name	Microsoft Windows 11 Home
Version	10.0.22631 Build 22631
My monitor is 27" 1440p OLED 240Hz, Windows scaling is at 100%, scaling is set to 'no scaling' in nVidia control panel.

On normal system startup with SCM auto starting, the menu appears under the window that I'm moused over.  Most of the time I can fix this by killing the SCM process and then restarting it, but not 100% of the time.  I tried enabling the High DPI feature, but it doesn't appear to make any difference.  I'm also on version 1.3.1 of SCM.

**Comment by AlexanderPro** [comment]
Hi @bleeme,

Does the menu always appear under the window or after some action? Why do you kill the SCM process, if there is "Exit" system tray menu? Please, attach gif image or video fragment to see more details.

**Comment by bleeme** [comment]
Hi,

Usually after my system starts up I notice that the SCM menu doesn't show
over the window that my mouse cursor is hovering over.  I used the term
"kill" loosely, I do select Exit from the system tray menu.  Additionally,
I'm also noticing that I don't need to exit SCM, but opening Settings help
with bringing the pop-up menu to the top.  I'll send you an example later
today.

*~Wei-min Lee~*

**Comment by bleeme** [comment]
the file is too large as an attachment so I'm sharing it from my google
drive...

 OmpPx97oTh.mp4
<https://drive.google.com/file/d/1FGrkquD7nPSbq5lUB24sY0R3RZy56mP1/view?usp=drive_web>


*~Wei-min Lee~*

**Comment by AlexanderPro** [comment]
Hi @bleeme,

Thank you for finding the bug. Please,  try version [1.3.2](https://github.com/AlexanderPro/SmartContextMenu/releases/download/v1.3.2/SmartContextMenu_v1.3.2.zip). I am not shure, but I hope it will fix the issue.

**Comment by bleeme** [comment]
Thank you, I'll give it a try tonight.

*~Wei-min Lee~*

**Comment by bleeme** [comment]
Hi Alexander,

This updated version fixed this issue.

Thank you!

*~Wei-min Lee~*
