### ISSUE TITLE
[Feature Request] Start Program Hotkey

### ISSUE THREAD

**Issue by MadeInUSAReview** [AlexanderPro/SmartContextMenu#25]
Please add the ability to trigger "Start Program" entries with a hotkey.

SCM is in my top 5 most useful programs on Windows - Thank you !

**Comment by AlexanderPro** [comment]
Hi @MadeInUSAReview,

Please,  try version [1.4.3](https://github.com/AlexanderPro/SmartContextMenu/releases/download/v1.4.3/SmartContextMenu_v1.4.3.zip).
