### ISSUE TITLE
Two monitors

### ISSUE THREAD

**Issue by oleg-sgh** [AlexanderPro/SmartContextMenu#5]
If two monitors are connected in the “extend” mode, then part of the menu goes to the second monitor. I have a TV, so I don't see the second part of the menu. Is it possible to display the menu on only one monitor?
![2024-01-02_112243](https://github.com/AlexanderPro/SmartContextMenu/assets/43082921/d98bd284-d3fd-4cd5-a9fc-69b05c914d84)

**Comment by AlexanderPro** [comment]
Hi @oleg-sgh,

Ok, I will fix this issue in the next version.

**Comment by oleg-sgh** [comment]
Added
Resizing and alignment does not work in PotPlayer. The player window and context menu are crumbling into artifacts.

**Comment by AlexanderPro** [comment]
> Added Resizing and alignment does not work in PotPlayer. The player window and context menu are crumbling into artifacts.

Could you attach a screenshot?

**Comment by oleg-sgh** [comment]
Changed the size of the window in the browser background. The size of the player has not changed. Part of the browser, the menu itself and a piece of the desktop remain.

Изменил размер окна на фоне браузера. Размер плеера не изменился.Остались часть браузера, само меню и кусочек рабочего стола.
![2024-01-18_085302](https://github.com/AlexanderPro/SmartContextMenu/assets/43082921/39c0a0b5-fdd4-4a04-82bd-97030c051c53)

**Comment by AlexanderPro** [comment]
Please, try version [1.1.0](https://github.com/AlexanderPro/SmartContextMenu/releases/download/v1.1.0/SmartContextMenu_v1.1.0.zip). It should fix the display of the menu on two monitors.

**Comment by AlexanderPro** [comment]
> Added Resizing and alignment does not work in PotPlayer. The player window and context menu are crumbling into artifacts.

К сожалению поправить изменение размера и другие пункты меню для PotPlayer скорее всего не получится, т.к. большая вероятность что у этого приложения есть логика ограничения размера окна. Повлиять на это в рамках SmartContextMenu не сможем. Но у меня на PotPlayer (64-Bit) версии 1.7.21595 не получилось воспроизвести такие ошибки.

**Comment by oleg-sgh** [comment]
У меня была версия PotPlayer моложе, даже обновил до свежей, но так и остались в нем глюки. 
Придется оставаться на SmartSystemMenu.
Если нет возможности их подружить, то оба моих запроса можно закрыть.  Плеер для меня в приоритете.

**Comment by AlexanderPro** [comment]
А в SmartSystemMenu эти пункты отрабатывают? Какая версия PotPlayer используется на приложенном скриншоте? Странно, что у меня для PotPlayer меняется и размер и выравнивание корректно. Может что-то в настройках у Вас стоит, я запускал сразу после установки не внося никаких изменений в настройки.

**Comment by oleg-sgh** [comment]
"А в SmartSystemMenu эти пункты отрабатывают?!"
Да, работает и я им пользуюсь с первых выпусков. Был один раз глюк после обновления SSM, но Вы его исправили. 

PotPlayer (64-битная версия)
Версия: 231220(1.7.22077)
Дата: Dec 21 2023 13:01:26

Сейчас скачал новый выпуск SmartContextMenu и запустил с настройками по умолчанию. Размер не работает, но и артефактов нет.

**Comment by AlexanderPro** [comment]
Очень хотелось бы найти причину ошибки) 

Скачал последнюю версию PotPlayer (64-Bit) 
Version: 231220(1.7.22073)
Build Date: Dec 20 2023 13:20:31

Версия чуть ниже чем у Вас. Пробовал делать запуск с разными скинами и без скинов (когда можно вызывать системное меню), с отображением playlist и без него, но во всех случаях изменение размера окна отрабатывает корректно. Возможно, что где то в меню настроек PotPlayer (Preferences...) внесены изменения у Вас. Но тогда не понятно почему отрабатывают пункты через системное сменю SmartSystemMenu.

**Comment by oleg-sgh** [comment]
Сейчас отключил все улучшайзеры в автозагрузке, перезапустил комп  и запустил SmartContextMenu с дефолтными настройками. Увы - не работает в PotPlayer-ре. 
А с моими настройками в других программах работают. 
Может поможет: в SSM тоже не всё гладко. Если отправить по координатам окно плеера в телевизор, то настройки, эквалайзеры и прочие окошечки, открывались на мониторе. Но то ладно, не принципиально.

**Comment by AlexanderPro** [comment]
@oleg-sgh Добрый день,

Если будет возможность, хотел бы попросить Вас сделать пару тестов:
1. Вызвать для PotPlayer пункт меню Information через SSM и SCM и приложить их скрины в это ишью.
2. Если вызывать пункт меню Alignment к примеру middle-center или сделать выравнивание через пункт (Alignment | Custom...), окно PotPlayer сломается в обоих случаях?

**Comment by oleg-sgh** [comment]
Здравствуйте. 

Русский мой родной и иностранные слова меня только путают )

1.  SSM
![SSM](https://github.com/AlexanderPro/SmartContextMenu/assets/43082921/289494c6-56a3-49b3-b603-4f3d3b19f728)

SCM

![SCM](https://github.com/AlexanderPro/SmartContextMenu/assets/43082921/28028177-d0e8-4626-b16c-0e3dbc863e57)

2. Выравнивание, как и изменение размера, в текущей версии SCM, не работают ни через меню, ни через горячие клавиши. 

3. В SSM, нет контекстного меню в скине по умолчанию. Все изменения PotPlayer производятся горячими клавишами.

**Comment by AlexanderPro** [comment]
Спасибо, вроде понимаю причину, похоже в SCM не правильно определяется окно PotPlayer. Еще небольшая просьба. Можете пожалуйста прислать скрин PotPlayer и пометить на нём то место где находится курсор мышки при вызове меню?

**Comment by oleg-sgh** [comment]
Посередине окна при воспроизведении видео. Пробовал и где попадёт. 

И ещё, скачал PotPlayer на виртуальную Windows 10. Там горячими клавишами меняется, а курсор как бы не видит плеера и размер меняется у окна самой виртуалки.

**Comment by AlexanderPro** [comment]
По поводу виртуальной машины не подскажу, тут главное чтобы SCM был запущен только внутри виртуальной машины и выключен на хостовой. Я пробовал запускать VirtualBox c WinXP и вроде всё работало. Подскажите, какая у Вас основная ОС где запускаете PotPlayer?

**Comment by oleg-sgh** [comment]
В виртуалке я просто посмотрел как будет работать. Там вообще некоторые вещи не работают, это не важно. 
Основная система Windows 7 с обновлениями по 31. 12. 2021.

**Comment by oleg-sgh** [comment]
Будут ещё вопросы - обращайтесь.

**Comment by AlexanderPro** [comment]
Добрый день!

Если будет возможность, попробуйте пожалуйста версию [1.2.1](https://github.com/AlexanderPro/SmartContextMenu/releases/tag/v1.2.1)

**Comment by oleg-sgh** [comment]
Здравствуйте. 
Старый файл настроек не подошел. При запуске выдал кучу ошибок, комп начал чудить - удалил всё,  сделал дефолтную портабельную. Навскидку -  Размеры меняются, работает выравнивание. Настрою своё заново - не суть.   
Полный перенос настроек и обкатку буду делать позже. Если что - напишу. Пока спасибо )

**Comment by AlexanderPro** [comment]
Всё что касалось файла настроек в этой доработке ничего не менялось. Может Вы как то руками не корректно отредактировали файл? Для сброса настроек достаточно удалить все в папке SmartContextMenu которая лежит в Roaming профиле текущего пользователя.

**Comment by oleg-sgh** [comment]
Здравствуйте. 
Докладываю. В PotPlayer часто использованные функции заработали. Если что вылезет, то сообщу. 
Меню и подменю SCM не вылазит за экран. 
В принципе, эту тему можно закрывать. Спасибо.

**Comment by AlexanderPro** [comment]
Благодарю, что помогли разобраться и найти причины ошибок!
